/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author -CHUANG-
 */
public class SwingZodiac extends javax.swing.JFrame {

    /**
     * Creates new form SwingZodiac
     */
    public SwingZodiac() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTanggal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtBulan = new javax.swing.JTextField();
        btnProses = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtZodiac = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Design Preview(FrmZodiac)");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Data"));

        jLabel1.setText("Tanggal");

        jLabel2.setText("Bulan");

        btnProses.setText("Proses!");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBulan, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btnProses, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnProses)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Deskripsi"));

        jLabel3.setText("Zodiac");

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtZodiac))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtZodiac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        int tanggal, bulan;

        tanggal = Integer.valueOf(txtTanggal.getText());
        bulan = Integer.valueOf(txtBulan.getText());
        if ((tanggal >= 21 && bulan == 3) || (tanggal <= 20 && bulan == 4)) {
            txtZodiac.setText("ARIES (21 Maret – 20 April)");
            txtArea.setText("- Sifat Umum : suka menonjolkan diri, senang beraktifitas, menyukai kepemimpinan.");

        } else if ((tanggal >= 21 && bulan == 4) || (tanggal <= 20 && bulan == 5)) {
           txtZodiac.setText("TAURUS (21 April – Mei 20)");
            txtArea.setText("- Sifat Umum : suka hak milik dan tanah, menyukai kesenangan fisik.");
        } else if ((tanggal >= 21 && bulan == 5) || (tanggal <= 20 && bulan == 6)) {
            txtZodiac.setText("GEMINI (21 Mei - 20 Jun)");
            txtArea.setText("- Sifat Umum : menjadi penjual jasa atau ide, senang komunikasi dan masalah kesusastraan.");
        } else if ((tanggal >= 21 && bulan == 6) || (tanggal <= 22 && bulan == 7)) {
            txtZodiac.setText("CANCER (21 Jun - 22 Jul)");
            txtArea.setText("- Sifat Umum : sangat peduli dalam urusan rumah dan keluarga, senang mengumpulkan benda berharga, sentimentil.");
        } else if ((tanggal >= 23 && bulan == 7) || (tanggal <= 22 && bulan == 8)) {
            txtZodiac.setText("LEO (23 Jul - 22 Aug)");
            txtArea.setText("- Sifat Umum : suka mengatur dan memerintah, menyukai media dan usaha kreatif, mengorganisir yang lain.");

        } else if ((tanggal >= 23 && bulan == 8) || (tanggal <= 22 && bulan == 9)) {
           txtZodiac.setText("VIRGO (23 Aug - 22 Sep)");
            txtArea.setText("- Sifat Umum : bekerja cepat dan tepat, sehat dan higienis, suka menganalisa yang lain.");
        } else if ((tanggal >= 23 && bulan == 9) || (tanggal <= 22 && bulan == 10)) {
           txtZodiac.setText("LIBRA (23 Sep - 22 Oct)");
            txtArea.setText("- Sifat Umum : menyenangi ide estetika, dalam seni dan lingkungan kerja yang berorientasi kemasyarakatan, adil pada siapa saja");

        } else if ((tanggal >= 23 && bulan == 10) || (tanggal <= 22 && bulan == 11)) {
            txtZodiac.setText("SCORPIO (23 Oct - 22 Nov)");
            txtArea.setText("- Sifat Umum : penuh misteri atau rahasia, menyukai problema dan riset.");

        } else if ((tanggal >= 23 && bulan == 11) || (tanggal <= 21 && bulan == 12)) {
           txtZodiac.setText("SAGITARIUS (23 Nov - 21 Dec)");
            txtArea.setText("- Sifat Umum : pengembara, mengejar filsafat, menyukai penelitian.");

        } else if ((tanggal >= 22 && bulan == 12) || (tanggal <= 19 && bulan == 1)) {
          txtZodiac.setText("CAPRICORN (22 Dec - 19 Jan)");
            txtArea.setText("- Sifat Umum : mengejar keuntungan bisnis (fiansial) dan status social.");
        } else if ((tanggal >= 20 && bulan == 1) || (tanggal <= 19 && bulan == 2)) {
             txtZodiac.setText("AQUARIUS (20 Jan - 19 Feb)");
            txtArea.setText("- Sifat Umum : mengejar segi kemanusiaan dan pengetahuan, menyukai aktifitas kelompok.");
        } else if ((tanggal >= 20 && bulan == 2) || (tanggal <= 20 && bulan == 3)) {
            txtZodiac.setText("PISCES (20 Feb - 20 Mar)");
            txtArea.setText("- Sifat Umum : menyukai hal-hal spiritual, kesenian dan lautan.");// TODO add your handling code here:
    }//GEN-LAST:event_btnProsesActionPerformed
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SwingZodiac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SwingZodiac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SwingZodiac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SwingZodiac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SwingZodiac().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtBulan;
    private javax.swing.JTextField txtTanggal;
    private javax.swing.JTextField txtZodiac;
    // End of variables declaration//GEN-END:variables
}
